# Generated by Django 2.0.3 on 2018-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disputa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('foto1', models.ImageField(upload_to='')),
                ('nome1', models.CharField(max_length=30)),
                ('votos1', models.IntegerField(default=0)),
                ('foto2', models.ImageField(upload_to='')),
                ('nome2', models.CharField(max_length=30)),
                ('votos2', models.IntegerField(default=0)),
            ],
        ),
    ]
