# Generated by Django 2.0.3 on 2018-03-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disputa',
            options={'verbose_name': 'Disputa', 'verbose_name_plural': 'Disputas'},
        ),
        migrations.AlterField(
            model_name='disputa',
            name='votos1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disputa',
            name='votos2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
