# Generated by Django 2.0.3 on 2018-03-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180328_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
