# Generated by Django 2.0.3 on 2018-03-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180329_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
